language: node_js
node_js:
  - 0.8
before_script:
  - npm install -g grunt-cli
  - npm install -g grunt-contrib-csslint
  - npm install -g grunt-contrib-htmlhint
  - npm install -g grunt-jscs
  - npm install -g grunt-contrib-jshint
